language: node_js
node_js: 7
script: yarn run compile
cache: yarn
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  skip_cleanup: true  # keep created files
  local_dir: gh-pages
  on:
    branch: master
